### ISSUE TITLE
除主页外其他页面无法直接访问

### ISSUE THREAD

**Issue by huobazi** [vincent178/ruby-china-mobile#1]
http://vincent178.github.io/topics/29865

路由在客户端,，从外部链接进来实际是没有这个页面的， 看来还是少不了 服务端 渲染

**Comment by vincent178** [comment]
是的，主要是github page的问题，github page拦截掉了这个请求不让客户端处理。其实不需要服务器渲染，只要用一个自建的静态文件服务器就可以了。

**Comment by huobazi** [comment]
@vincent178  你好，
自建的服务器用什么手段让这个请求在客户端处理？
404 的时候 render 一段 js?

**Comment by vincent178** [comment]
配置静态文件服务器，找不到的url就使用index.html就可以了，后续的router由客户端的react-router处理

**Comment by huobazi** [comment]
哦，明白了。那这用来做单独的 mobile site 或者 微信site 等是个不错的选择，SEO 还是需要主站来服务器端渲染来做。

**Comment by vincent178** [comment]
对的 😄
